### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by MaryAGeorgescu** [lazerwalker/twison#14] opened 2017-01-26 22:45 UTC
Really bummed, Twine 2 is still not allowing me to use the converter. I can't even see it if I try ignoring the error by attempting change the format from within the story anyway.

![screenshot 2017-01-26 17 41 31](https://cloud.githubusercontent.com/assets/20546785/22353512/db8d7ba6-e3ee-11e6-9992-a60010fb4e4e.png)

**Comment by lazerwalker** [comment] 2017-01-27 17:09
Are you using the downloadable version of Twine 2, or the web-hosted one? If the latter, what web browser are you using?

**Comment by MaryAGeorgescu** [comment] 2017-01-27 18:48
Hey Mike!

Im using google chrome on a mac but I tried on a windows computer on chrome
as well with no luck. I might have even tried just internet explorer as
well with no responce. I stayed away from firefox assuming it would be
problematic.

I haven't tried the downloadable version, should I give that a try?

**Comment by lazerwalker** [comment] 2017-01-27 20:34
Naw, it should work fine in the web version. I was able to get it working in Chrome on a mac that had never used Twine before, which is super weird.

When you get that error adding the story format, can you open the Chrome Web Inspector (right click anywhere on the page and select "Inspect") and see if any errors show up in the JavaScript console? (Or even just send a screenshot of the whole page with the inspector open). Since I can't seem to reproduce this myself, it'd be useful to see what errors are actually being triggered in the code.

**Comment by MaryAGeorgescu** [comment] 2017-01-28 17:09
I believe the issue is coming from https but have a look

![screen shot 2017-01-28 at 5 04 08 pm](https://cloud.githubusercontent.com/assets/20546785/22398236/56e05e8e-e57c-11e6-9f41-d1563091747b.png)

**Comment by lazerwalker** [comment] 2017-01-28 17:49
Yep, that's likely. Try explicitly loading the format from the non-HTTPS version at http://twinery.org/2/ ?

(If that's all it is, I can find HTTPS hosting for the format file.)

**Comment by MaryAGeorgescu** [comment] 2017-01-29 20:36
yup! It works now, this was definitely related to https. Thank you!

**Comment by lazerwalker** [comment] 2017-01-29 21:01
Great! If it's preferable, that means it should also work fine from the downloadable version.

I'm gonna close this for now (and add a note to the README + work on finding https hosting for the format file), but feel free to open more issues if you run into anything else.

**Closed by lazerwalker** 2017-01-29 21:01 UTC
